### ISSUE TITLE
Option for clock to show or hide minutes, AM hours, PM hours

### ISSUE THREAD

**Issue by jubonhomme** [llaske/sugarizer#903] opened 2020-12-12 10:35 UTC
Is it possible to add a button to show or hide the hours AM and PM hours and minutes with the corresponding colors?
Here is another example of an interactive clock that I find very complete.
http://www.informatique-enseignant.com/horloge-interactive-pour-apprendre-heure/
![image](https://user-images.githubusercontent.com/29262866/101981465-57f97480-3c6d-11eb-8cd6-76804499d8b1.png)

**Comment by llaske** [comment] 2020-12-13 21:23
Good idea!

**Comment by codescientist703** [comment] 2020-12-22 12:57
hi @jubonhomme , Can I work on this if you are not working ? this looks like a nice feature to implement.

**Comment by jubonhomme** [comment] 2020-12-22 13:43
Yes you can... 
I am not a programmer, just a teacher with some ideas and proposals
I used this old clock a few years ago but it only works with flash player...
And now that I know Sugarizer, I would really like to find these options on the clock.
Tank you !

**Comment by sarthak-g** [comment] 2020-12-22 15:06
Solved this in pull request #910

**Comment by llaske** [comment] 2020-12-26 21:07
Fixed in https://github.com/llaske/sugarizer/pull/910
@jubonhomme you could test the fix on the dev platform: https://dev.sugarizer.org

**Comment by jubonhomme** [comment] 2020-12-26 22:25
Merci beaucoup pour ce travail et la réactivité !

Juste une petite remarque, l'affichage du nombre des minutes (60, 15 et 45) sur les côtés et en haut, est légèrement coupé sur l'affichage à 100%... il faudrait élargir un petit peu le cadre.
![image](https://user-images.githubusercontent.com/29262866/103159904-48cb0880-47cf-11eb-9503-870fbbb33b82.png)

Sur mon écran ça passe bien si je zoom à partir de 130%
![image](https://user-images.githubusercontent.com/29262866/103160029-9ac05e00-47d0-11eb-9957-d5aafd9b1234.png)

Ou si je sort du plein écran pour la fenêtre du navigateur.
![image](https://user-images.githubusercontent.com/29262866/103160105-67320380-47d1-11eb-99e3-4e43a07d812a.png)


Serait-il possible de séparer l'affichage des heures 24h et des minutes sur deux boutons différents.
Un bouton pour l'affichage des minutes
un autre bouton pour l'affichage des heures (13h/24h)

On ne travaille pas forcément les deux notions en même temps, je pense que ça serait plus clair de pouvoir afficher les deux indépendamment. 

Merci encore !

**Comment by sarthak-g** [comment] 2020-12-27 08:32
@jubonhomme Can you try once after clearing all cookies.
In my laptop, it is showing correct with 100% zoom.

![clock_am_pm_display](https://user-images.githubusercontent.com/42293606/103166847-262b0500-484c-11eb-8eca-fc12c15581b0.JPG)

**Comment by llaske** [comment] 2020-12-27 10:28
I'm agree that may be we could add some pixel margin to the top. It seems specifically visible on Firefox.

![Peek 27-12-2020 11-18](https://user-images.githubusercontent.com/981841/103168703-b578ee00-4835-11eb-9b88-b4726bf9bc1a.gif)

Regarding splitting options 12/24h and showing minutes, I'm usually not in favor to add too much buttons in the toolbar (to avoid a too complex UI). BTW you're right these features are not really related.

@sarthak-g could you split the feature in two different buttons? 
The first one to display 24h hours (may be you could redraw the icon to do a switch between 12/24 instead of AM/PM).
The second one to display minutes.

**Comment by sarthak-g** [comment] 2020-12-27 11:51
@llaske I'm not able to reproduce first issue on firefox and chrome. Is I'm missing something?

Uploading clock_activity_screen.mp4…

**Comment by jubonhomme** [comment] 2020-12-27 13:36
I tested with linux (Ubuntu 20.04) Firefox and Chrome, always the same issue.

But it's Ok with win10 for Chrome and Firefox... 

It's only with Ubuntu

**Comment by sarthak-g** [comment] 2020-12-27 18:14
Thanks @jubonhomme  for confirming.
I tried with Ubuntu 19.04 but not able to reproduce the issue. May be it's only there in 20.04
Although I tried to solve it in #915

**Comment by llaske** [comment] 2020-12-27 20:52
> I tested with linux (Ubuntu 20.04) Firefox and Chrome, always the same issue.
> It's only with Ubuntu

More a resolution issue because my test above was on Ubuntu 20.04 with Firefox.

**Comment by jubonhomme** [comment] 2020-12-27 22:51
It happens only when the window is full screen... it's strange 

A new video capture with chrome, if that can help you 
https://user-images.githubusercontent.com/29262866/103181121-c3625980-489d-11eb-8c1d-89bc5c28cc7f.mp4

**Comment by sarthak-g** [comment] 2020-12-28 12:07
Tried with firefox on 20.04 but not able to reproduce it. I reduced clock radius when displaying minutes in #915 
Hope it resolves the issue.

**Comment by llaske** [comment] 2020-12-30 10:50
@jubonhomme the new version is online on https://dev.sugarizer.org 
Please test the new feature (split of 24h/minutes buttons) and fix on size.

**Comment by jubonhomme** [comment] 2020-12-30 16:30
Perfect !
![image](https://user-images.githubusercontent.com/29262866/103367150-a65b9f80-4ac4-11eb-8cc3-7cf9b602a221.png)

**Closed** 2021-04-27 19:44 UTC
Labels: enhancement, to be release
