### ISSUE TITLE
Improve Responsiveness of the Fototoon Activity

### ISSUE THREAD

**Issue by anshuldutt21** [llaske/sugarizer#576] opened 2020-01-24 14:21 UTC
The Fototoon activity could be made more responsive by using media queries. The main canvas could be restructured so as to fit the smaller screens.

![Screenshot from 2020-01-24 19-52-13](https://user-images.githubusercontent.com/45336622/73075967-23f55380-3ee3-11ea-94ec-9f96efbdc27c.png)

**Comment by s-mag** [comment] 2020-01-24 16:55
@anshuldutt21 This issue is a duplicate of issue #559 .Please close this issue.

**Comment by llaske** [comment] 2020-01-25 09:04
I'm agree with @s-mag . See also https://github.com/llaske/sugarizer/issues/422

**Closed** 2020-01-25 09:35 UTC
