### ISSUE TITLE
when connected to server, activities get shared automatically 

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#810] opened 2020-05-29 16:25 UTC
when connected to server, activities get shared automatically without even clicking network button.
I tested with both dev.sugarizer.org and local server on even different laptops in `dev` branch . 
also tested on [https://dev.sugarizer.org/](https://dev.sugarizer.org/)
The issue doesn't occur in `master` branch.
from this issue several activities are having problem like In last one loses activity we are not able to play vs computer mode(single player mode).
see below
![ezgif com-video-to-gif (14)](https://user-images.githubusercontent.com/40318927/83281840-51863c80-a1f6-11ea-9172-45b7bd7c4368.gif)

The issue was not there until some weeks ago ( when i was developing chess activity).

will be very helpful if other contributors can verify this issue.

**Comment by dhruvmisra** [comment] 2020-05-29 18:17
Hey @prakashujjwal1010, I tried to replicate the issue on my side but I wasn't successful. The activity was not being shared automatically after opening it. I tried running the local server and also on https://dev.sugarizer.org/. Could you explain the steps you followed? Or could you mention other activities you are facing this issue with?

I did notice a different strange behavior: If I click on the single-user mode (left one with icon: `zoom-home.svg`) in the presence palette, it still shares the activity. Only this time the styling of the presence palette is a little off, as can be seen in the GIF uploaded by you.

I think it's happening after `lib/sugar-web/presence.js` was updated to show the connected users. The problem you are facing might also be linked to this. @llaske, can you confirm the odd behavior on your side?

**Comment by prakashujjwal1010** [comment] 2020-05-29 18:36
Steps to replicate the issue:
- Log in as a new user,
- open any activity and share it by clicking on the network palette.
- now stop the activity
- now when you open any other activity , it will get shared automatically

**Comment by dhruvmisra** [comment] 2020-05-29 18:56
Weird, I still couldn't replicate it. :(
I tried it with a different browser too. Try clearing your browser cache, maybe that'll help?

**Comment by prakashujjwal1010** [comment] 2020-05-29 19:11
yes, i tried clearing cache also...but still getting the same.
i even tested it on my phone browser, still getting the issue...
:(

**Comment by llaske** [comment] 2020-05-29 21:10
@prakashujjwal1010 could you try with different network speed (choose from the Network sheet in the Chrome dev window)?

**Comment by prakashujjwal1010** [comment] 2020-05-30 06:57
@llaske @dhruvmisra please try this :

![ezgif com-video-to-gif (15)](https://user-images.githubusercontent.com/40318927/83321840-5be51c80-a270-11ea-95d0-0aac26120474.gif)

- go to [https://dev.sugarizer.org/](https://dev.sugarizer.org/)
- sign in as a new user
- open paint activity from home view or list view

( i've tested this on different laptop )
yes, @llaske  i have tried with different speeds on different laptops with different internet connections.

**Comment by dhruvmisra** [comment] 2020-05-30 07:18
Yes! It happened with me too. Paint automatically shared an instance. I opened Last One Loses, it didn't  share it automatically but once I shared it myself and closed the activity, every time I open it again it shares it automatically.

**Comment by llaske** [comment] 2020-05-30 14:51
Unfortunately I can't reproduce on my side, even with the detailed steps :-(

I've fixed in https://github.com/llaske/sugarizer/pull/813 the related issue https://github.com/llaske/sugarizer/issues/811.
@prakashujjwal1010 @dhruvmisra Could you check if it fix also this issue on your side?

**Comment by prakashujjwal1010** [comment] 2020-05-30 20:19
@dhruvmisra , yes you are right the issue doesn't exist when connected to local remote `sugarizer-server` but when connected to `dev.sugarizer.org`, it is there.

@llaske , when connected to `sugarizer-server` it solves the #811  on my side.

but when connected to `https://dev.sugarizer.org/` now network button is not working means the activity is not getting shared on clicking network button. :(

don't know the reason behind this difference when connected to different servers, as it should behave same

**Comment by llaske** [comment] 2020-05-31 09:05
@prakashujjwal1010 thanks for the detailed description of the issue. It helps me a lot to understand the problem. The difference with a local server and `dev.sugarizer.org` - and also the reason why I can't reproduce the issue on my side - is that it depends of the network latency to accept connection.
I've finally reproduce the issue on my side by forcing my local server to 1 second wait before accepting connection ([here](https://github.com/llaske/sugarizer-server/blob/dev/api/middleware/presence.js#L75) for information).
With this one second latency I was able to reproduce both issue: automatic share and disable of network buttons.

I've updated the https://github.com/llaske/sugarizer/pull/813 PR to integrate the fix.

@prakashujjwal1010 @dhruvmisra could you test again on your side to see if it works now?

**Comment by dhruvmisra** [comment] 2020-05-31 11:06
I changed the network throttling in Chrome Dev tools to 'Mid-tier mobile' and I was able to reproduce the issue using local server as well. 

@llaske The PR does fix the issue. No problems after network throttling as well.

Also thanks to @prakashujjwal1010, now that I have your attention on Last One Loses activity, I think the workflow after sharing the activity can be improved. As you can see, the user who shares the activity can't play the game until some other user connects and is also stuck if the connected user leaves in the middle. (As pointed out by @sarthak-g in #722). I think the solution proposed to let the user play against computer is good and feels intuitive.
I agree that the duration of the LOL game is small but I think that shouldn't be a reason to provide a bad experience (restarting to play if activity got shared) to the user. What do you say?

**Comment by prakashujjwal1010** [comment] 2020-05-31 15:45
@llaske , the issue is fixed now, on my side. thanks.
@dhruvmisra , yes I think letting user play until another user connects or if opponent leaves in the middle is a good idea.

**Comment by llaske** [comment] 2020-06-01 20:19
Thanks to both of you.

@dhruvmisra I'm agree regarding Last One Loses activity. Please fill an issue regarding that.

**Comment by llaske** [comment] 2020-06-02 20:41
Fixed in https://github.com/llaske/sugarizer/commit/95e9cd2b0f26d48a058b01fd7928c9ee97928467

**Closed** 2020-09-23 19:33 UTC
Labels: bug, to be release
