### ISSUE TITLE
Resizing textarea in activity palette looks ugly

### ISSUE THREAD

**Issue by kartikaysaxena** [llaske/sugarizer#1303] opened 2023-03-07 15:44 UTC
For elaboration please have a look below

See how textarea on resizing falls out of div and also at the bottom it makes the other buttons go off the screen
<img width="1440" alt="Screenshot 2023-03-07 at 9 07 41 PM" src="https://user-images.githubusercontent.com/120778728/223472480-abdb44cb-0304-4302-b042-c5abe9c875e2.png">

My fix(How it should behave)
It should resize only in vertical direction like this
<img width="1440" alt="Screenshot 2023-03-07 at 9 08 19 PM" src="https://user-images.githubusercontent.com/120778728/223472811-06f80ba9-5f1f-4435-ac95-3ac8f2942f3e.png">

**Comment by Shruti-codes236** [comment] 2023-03-17 14:58
Can I work on this issue if this isn't resolved yet?

**Comment by llaske** [comment] 2023-04-10 20:39
The issue is the same for all activities.

**Comment by llaske** [comment] 2024-02-22 21:10
Fixed in https://github.com/llaske/sugarizer/pull/1522

**Closed** 2024-02-22 21:20 UTC
Labels: enhancement, to be release
