### ISSUE TITLE
Disabling Text selection for buttons 

### ISSUE THREAD

**Issue by SiddheshKukade** [llaske/sugarizer#1151] opened 2023-01-22 10:08 UTC
### Problem :

We can select the text of the buttons in website.

[screen-capture.webm](https://user-images.githubusercontent.com/65951872/213910254-ab5aaa2f-5955-448d-b969-e73565832fe3.webm) 

Note: Please use chrome browser if the video is not visible on firefox 👍🏻 

As we can see from the video that we can select the text of the buttons on the website. This is not a good practice and can lead user in confusion whether to click that button or not. 

### Solution : 
I'd remove the text selection option

Please assign this issue to @SiddheshKukade

**Comment by adarrssh** [comment] 2023-01-26 06:41
@SiddheshKukade, you don't need to ask for permission to work on any issue, you can make the changes and make a pr for that.

**Comment by llaske** [comment] 2023-01-28 10:45
@SiddheshKukade, sure.
But should be fixed on the Sugar.IconButton component, not in each screen.

**Comment by llaske** [comment] 2023-01-28 10:47
@adarrssh yes but it's better to wait that the issue is approved before starting to work on a PR.

**Comment by UtkarshSiddhpura** [comment] 2023-01-28 16:08
Also intro js has it's own styling in all activities that'd be a bulk refactor and will also have to change the migration guide from bootstrap-tour
@llaske share your views

**Comment by llaske** [comment] 2023-01-28 16:39
@UtkarshSiddhpura it's not a major point. I think we could ignore this issue in tutorial.

> Can you please tell me the reason why all activities can't share a lib together like one intro js for all

For modularity and isolation reason, each Sugarizer activity is a separate HTML application and can use a different Javascript framework (ReactJS, Vue.js, VanillaJS, ...). Have a look on [architecture page](https://github.com/llaske/sugarizer/blob/dev/docs/architecture.md) for more information about that.

**Comment by llaske** [comment] 2023-01-28 20:23
Fixed in https://github.com/llaske/sugarizer/pull/1169

**Comment by Ankitsharma991** [comment] 2023-01-31 20:57
I want to work on this issue, can anyone assign this to me?

**Comment by llaske** [comment] 2023-01-31 21:00
@Ankitsharma991 it's already fixed.

**Closed** 2023-03-28 20:17 UTC
Labels: enhancement, to be release
