### ISSUE TITLE
Harsh Sound in TamTam Micro activity in keyboard mode on Firefox and Safari

### ISSUE THREAD

**Issue by s-mag** [llaske/sugarizer#564] opened 2020-01-16 19:34 UTC
To reproduce : Change any instrument and play 2 sounds together..
You will hear distorted sounds throughout the activity.
@llaske Can you reproduce this bug...

**Comment by llaske** [comment] 2020-01-18 10:13
I'm not able to reproduce it. I'm trying with guitar for example.

**Comment by s-mag** [comment] 2020-01-18 10:14
> I'm not able to reproduce it. I'm trying with guitar for example.

Will send you a link to the video with sound in a bit...

**Comment by s-mag** [comment] 2020-01-18 12:48
@llaske After 5-6 clicks together [this](https://imgur.com/OtO89z9) happens.

**Comment by llaske** [comment] 2020-01-19 09:39
I reproduced it on Firefox thought it perfectly work on Chrome. Could you confirm you've tested it on Firefox?

**Comment by s-mag** [comment] 2020-01-19 09:55
> I reproduced it on Firefox thought it perfectly work on Chrome. Could you confirm you've tested it on Firefox?

Yes it is in firefox, no problem in chrome. I forgot to mention that!

**Comment by llaske** [comment] 2020-01-22 12:00
For information, same issue on Safari

**Comment by pidddgy** [comment] 2020-01-25 04:40
very very interesting bug.... when I reproduce the bug then play audio on other websites that is distorted and crackly too. tested on firefox

**Comment by s-mag** [comment] 2020-01-25 08:42
> very very interesting bug.... when I reproduce the bug then play audio on anything else e.g. other tabs, spotify desktop app, system noises that is distorted and crackly too, until i close the tab with sugarizer. tested on firefox

Yes, this might be internal system error in firefox aswell. I am not sure btw

**Comment by s-mag** [comment] 2020-01-25 08:48
@llaske @pidddgy according to http://forums.mozillazine.org/viewtopic.php?f=38&t=2542145 forum The issue comes in Firefox 15

**Comment by llaske** [comment] 2020-01-25 09:12
@s-mag This Firefox issue is very old, I'm not sure it's related.
@pidddgy Is there a way to reproduce the problem with just a Tone.js sample?

**Comment by s-mag** [comment] 2020-01-25 09:36
> @s-mag This Firefox issue is very old, I'm not sure it's related.
> @pidddgy Is there a way to reproduce the problem with just a Tone.js sample?

Oh yeah it’s very old...

**Comment by pidddgy** [comment] 2020-01-27 21:21
perhaps could be related to 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio? i'm really not sure. I tried changing the play code in piano.js to:
```js
Tone.context.resume().then(() => {
            var player = new Tone.Player('./audio/database/'+currentPianoMode+".mp3");
            var pitchShift = new Tone.PitchShift({
                pitch: pitchMap[pitchName]
            }).toMaster();
            player.connect(pitchShift);
            player.autostart = true;
            console.log('playing');
        })
```

as according to https://stackoverflow.com/questions/50281568/audiocontext-not-allowed-to-start-in-tonejs-chrome but that didn't do anything. I am getting console warnings about `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

**Comment by llaske** [comment] 2020-01-28 21:29
I know this limit regarding playing sound. It happens in some case in other activities.
But I don't think it's related to our problem. Plus, the problem is on Firefox, not Chrome.
Will be interested to try to reproduce the issue on a simple Tone.js sample so we could ask to Tone.js community.

**Comment by pidddgy** [comment] 2020-01-29 05:30
@llaske https://github.com/pidddgy/tonejstest i've written up a short demonstration here

**Comment by llaske** [comment] 2020-01-29 08:29
Nice! Could you open an issue in ToneJS repo?

**Comment by llaske** [comment] 2020-01-30 13:30
@pidddgy did you see the answer from ToneJS community? Very interesting! 
Guess your current code could be improved to try to reuse ToneJS objects.

**Comment by llaske** [comment] 2020-02-13 14:42
@pidddgy any progress on it? I've got a new TamTam mode planned but don't want to launch before this issue is fixed

**Comment by pidddgy** [comment] 2020-02-14 22:20
sorry, I haven't made significant progress on the issue. I'll likely be taking a break from open source for the next few months to focus on OI contests/school. 

For anyone interested in tackling this issue, the problem is that `Tone.Player` objects are being created on every play and not being `dispose`d of. To solve this issue I think the solution is to create a global map of `Tone.Player` objects, perhaps through the `Tone.Players` class which is supposed to be a collection of `Tone.Player`s, and start the appropriate player on click. I have tried setting an interval to dispose of a player if it is currently not playing, but that is too slow and while improves the issue it will bug out if you click really fast.

relevant reading:
https://tonejs.github.io/docs/13.8.25/Player
https://tonejs.github.io/docs/13.8.25/Players
https://github.com/pixijs/pixi-sound/issues/65
https://github.com/Tonejs/Tone.js/wiki/AudioContext

I'm not quite familiar with the Tone.js library, but I think it's just a matter of "getting it to work" and finding the right combination of code.

**Comment by llaske** [comment] 2020-02-16 21:36
Thanks for your help @pidddgy. I've fixed it in https://github.com/llaske/sugarizer/commit/5f1889a88a8ae25c750cc6743ef23aa5ccd6e49a

**Closed** 2020-03-28 08:14 UTC
Labels: bug, to be release
