### ISSUE TITLE
Tutorial button hidden on login screens

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#697] opened 2020-03-13 15:24 UTC
On all touch devices, the tutorial button is hidden and the entire UI is shifted upwards on login/create user screens. See here:

![loginHelpIssue](https://user-images.githubusercontent.com/40134655/76633646-0d768a80-656b-11ea-8112-c24d297aac03.gif)

This was the case for existing users. The issue can also be replicated for a new user if the login screen is refreshed once.

![loginHelpIssue2](https://user-images.githubusercontent.com/40134655/76634249-0c922880-656c-11ea-80b8-2e424f8591db.gif)

I'm working on a fix.

**Comment by llaske** [comment] 2020-03-13 16:22
It's not a bug, it's an expected feature on touch devices.
On real device (tablets/smartphone), half of the screen is used by a virtual keyboard. So we need to scroll up.

**Comment by dhruvmisra** [comment] 2020-03-13 16:52
I don't think shifting the UI elements is required as the real devices shift the entire UI upwards automatically to make space for the virtual keyboard. See here:

![20-03-13-22-14-43](https://user-images.githubusercontent.com/40134655/76642208-d0b19000-6578-11ea-9173-3e092607e985.gif)

And you can clearly see that the help button is mostly hidden here.
The solution I proposed in #698 would fix it.

![20-03-13-22-15-28](https://user-images.githubusercontent.com/40134655/76642350-0eaeb400-6579-11ea-8fe4-566d6cc992e2.gif)

**Comment by llaske** [comment] 2020-03-13 17:03
Behavior on a mobile web browser is not the same than in a Cordova Webview app.
Did you test your change in the Android app?

**Comment by dhruvmisra** [comment] 2020-03-13 17:10
I haven't done that yet. May I know how can I test the changes in the Android app?

**Comment by llaske** [comment] 2020-03-13 20:14
Sure. I suggest you to use the [Sugarizer APK builder](https://github.com/llaske/sugarizer-apkbuilder).

**Comment by dhruvmisra** [comment] 2020-03-14 18:52
I'm encountering an error while building the apk
```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /sugarizer-cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=937565a5-5dae-424d-a577-b878e2a59ae6.1, currentDir=/sugarizer-cordova}
Attempting to read last messages from the daemon log...
Daemon pid: 1310
  log file: /root/.gradle/daemon/3.3/daemon-1310.out.log
----- Last  20 lines from daemon log file - daemon-1310.out.log -----
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateSigningDebug
:packageDebug
----- End of the daemon log -----
```

**Comment by llaske** [comment] 2020-03-15 09:55
Hmmm. Is it the result of Sugarizer APK builder?
The docker container is very huge and take memory. It could be the cause of the unexpected crash of Gradle. Try to allocate more resource to docker.

**Comment by dhruvmisra** [comment] 2020-03-15 16:41
Thanks @llaske, allocating more memory worked. I checked the APK and I agree that the UI needs to be scrolled up as you mentioned. My major concern still surrounds the disappearance of tutorial icon on such devices.
My current solution #698 removed the UI scroll, but I've updated the PR with my latest commit restoring the UI behavior and at the same time fixing the tutorial icon disappearance. Please review.

**Comment by llaske** [comment] 2020-03-31 20:11
Fixed in https://github.com/llaske/sugarizer/pull/698

**Comment by llaske** [comment] 2020-04-04 19:58
Revert back the fix in https://github.com/llaske/sugarizer/commit/4866d97fae314d5770e509e7a4bbe3350ed8325e because it don't work on iOS: the help button is no longer visible.

BTW https://github.com/llaske/sugarizer/pull/740 solve the issue too because the screen size is reduced so the help button become visible.

**Comment by dhruvmisra** [comment] 2020-04-04 21:06
That's right, this shouldn't be a problem anymore on Android. Would look for a solution similar to #740 for iOS.

**Closed** 2020-09-23 19:33 UTC
Labels: enhancement, to be release
