### ISSUE TITLE
Memorize responsive seems broken on phones

### ISSUE THREAD

**Issue by mikklfr** [llaske/sugarizer#106] opened 2017-03-09 20:41 UTC
The paint activity button seems to have troubles with small screen.
Some CSS should be able to fix it.

**Comment by dinesh-sirvi** [comment] 2017-03-12 22:26
Couldnt able to reproduce the issue, Can u elaborate it more or provide me the steps to reproduce it?

**Comment by mikklfr** [comment] 2017-03-12 22:29
My bad, it's the memorize activity. I'm updating the issue.

You can see the quit button going out of the toolbar on this photo.

https://www.facebook.com/photo.php?fbid=10154521813268510&set=pcb.10154521813863510&type=3&theater

**Comment by dinesh-sirvi** [comment] 2017-03-12 22:40
I'll Check it....

**Comment by rajeevravindran** [comment] 2017-03-13 10:47
Can't reproduce the problem. @mikklfr Can you give the viewport dimensions of the browser on your phone?

**Comment by mikklfr** [comment] 2017-03-13 10:52
I've been able to reproduce using the Galaxy S5 viewport in Google Chrome debug. 640 x 360

**Comment by rajeevravindran** [comment] 2017-03-13 11:23
![image](https://cloud.githubusercontent.com/assets/10564476/23852351/56a179cc-080d-11e7-8fbc-e5a02cc82af5.png)

`.toolbar{
 padding : 0 50px;
}`

This solves it. Creating a PR

**Comment by mikklfr** [comment] 2017-03-13 13:22
Better but I still have issues using
 590px  <=  width <= 638px

**Comment by rajeevravindran** [comment] 2017-03-13 13:39
Yes. Maybe an @media query for this range? 570px - 638px

**Comment by rajeevravindran** [comment] 2017-03-13 15:31
![image](https://cloud.githubusercontent.com/assets/10564476/23861468/1f5b9268-0830-11e7-900a-807885dd80de.png)
Seems to be working. I'll make a PR? 
`@media screen and (min-width: 590px) and (max-width: 638px){
  .toolbar{
    padding: 0 25px;
  }
}`

**Comment by utkarsh-raj** [comment] 2019-02-21 18:27
Some insight - 

- The responsiveness is broken across several activities (including Memorize, the original activity in question)

- In some other activities, the Stop button simply goes away on some viewports, which can be verified by the Google Chrome Developer Tools

- The issue is also there for several modern devices like the iPhone X

Probably some CSS for modern viewport breakpoints should be able to fix this. But the important point is that the issue has a much broader scope than only Memorize. I am currently working on this and some reviews will be great :)

![screenshot from 2019-02-21 23-53-25](https://user-images.githubusercontent.com/28586681/53192356-46785000-3634-11e9-8a6b-1124fc5286e0.png)
![screenshot from 2019-02-21 23-52-04](https://user-images.githubusercontent.com/28586681/53192369-4d9f5e00-3634-11e9-8d12-7a0cf3677d32.png)

**Comment by llaske** [comment] 2019-02-21 21:22
Here's few insights regarding Sugarizer responsive policy:

1. The preferred way to run Sugarizer on mobile devices is via the iOS and Android app.
2. Sugarizer UI is adapted to screen larger than longer (landscape), this rule is forced on iOS and Android apps. In browser in portrait mode (like in your screen capture), nothing is required from activities today.
3. Sugarizer is not adapted today to smartphone, it's not only related to toolbar but also to the size of graphical UI items in activities (too small to be handle with fingers). Sugarizer activities running on smartphone should do the best to run: minimal behavior is to be able to be launched and stopped. Nothing more is required. And of course, due to 1., this requirement is in landscape mode.

**Comment by utkarsh-raj** [comment] 2019-02-22 18:08
Many thanks for the insights @llaske , I missed the point that the Android and iOS Application are a better way for Sugarizer on mobile devices. This basically means that the disappearing stop button is not an issue for small viewports.

So maybe the issue can be safely closed ?
Or the CSS breakpoints should be edited for the Memorize Activity ? (and other related activities ?)

**Comment by llaske** [comment] 2019-02-23 10:06
@utkarsh-raj it should not be closed if the issue concern the Android version and forbid Memorize to follow the minimal behavior: to be able to be launched and stopped.

**Comment by utkarsh-raj** [comment] 2019-02-23 19:31
From what I could test, the Android version works fine for standard viewports and the minimal expected behaviour is satisfied. Any specific viewport resolution @llaske ?

**Comment by llaske** [comment] 2019-02-23 21:38
Sugarizer Core was thought to be responsive until 480x320 because it was the resolution of the Firefox OS Keon phone. But this resolution it's not supported by all activities. Plus I don't think this resolution make sense today. So the minimum should probably be twice this resolution.

**Comment by utkarsh-raj** [comment] 2019-02-24 08:47
All right I will get to work on this. A bit of research on my part is required. Thanks for the pointers @llaske :)

**Comment by utkarsh-raj** [comment] 2019-02-24 12:59
https://github.com/llaske/sugarizer/pull/279#issue-255672546

The required file is identified already by @rajeevravindran .I have verified and implemented the required Media Queries. The PR now also fixes the responsiveness issues for all major viewports.

**Comment by llaske** [comment] 2019-02-25 20:51
Fixed in https://github.com/llaske/sugarizer/pull/282

**Comment by llaske** [comment] 2019-09-26 20:41
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241

**Closed by llaske** 2019-09-26 20:41 UTC
Labels: bug, to be release
