### ISSUE TITLE
Miss a tutorial on Abecedarium activity

### ISSUE THREAD

**Issue by zupercat** [llaske/sugarizer#378] opened 2019-09-22 09:46 UTC
It seems that some activities don't have a description/tutorial and while some activities are easy to figure out, others, like the Abecedarium activity can be very confusing and hard to navigate.

**Comment by eMBee** [comment] 2019-09-22 09:54
i am exploring sugarizer with @zupercat and other students,

we are exploring the code to find out where to put a description for an activity.

it appears that activity/activity.info might be a suitable place.

**Comment by llaske** [comment] 2019-09-22 20:17
Thanks for your feedback @zupercat and @eMBee .
You could find a short description of all activities, including Abecedarium, on the Sugarizer list view (click on the ? button on each line).

![image](https://user-images.githubusercontent.com/981841/65393815-1473cb80-dd86-11e9-8fb5-72e0a77d9cb1.png)

Some activities have also a detailed tutorial included. 
BTW most of the time, children never launch the tutorial, they just click to explore. Plus, not all Sugarizer user know how to read. So an intuitive UI is often more important than a documentation.

Do you have some specific suggestion to improve Abecedarium UI?

**Comment by SamuraiNights** [comment] 2019-10-02 06:31
I think the problem is that when you start a program, like the Abecedarium, it is unclear which button you should press and what it does. A good example is the tutorial on the starting page of Sugarizer. If we were to add that to all the programs, then it would be much easier to use them.

**Comment by jlc-png** [comment] 2019-10-02 09:12
We've try to add a new tutorial button in Abecedarium, but the button was invisible.We copied the code from the Labyrinth activity.It's not clear what else we need to add.
We guess we need bootstrap-tour-standalone.min.css and some other things.

**Comment by llaske** [comment] 2019-10-02 12:41
Ok so I've renamed the issue "Miss a tutorial on Abecedarium activity" to better match your request.
You're right, to add a tutorial you need to use the [bootstrap tour](http://bootstraptour.com/) library.
You should include the CSS file (see [here](https://github.com/llaske/sugarizer/blob/dev/activities/LabyrinthJS.activity/index.html#L14)) and the JS file too (see https://github.com/llaske/sugarizer/blob/dev/activities/LabyrinthJS.activity/index.html#L18). 
Then you will have to implement the call to the tutorial itself, have a look [here](https://github.com/llaske/sugarizer/blob/dev/activities/LabyrinthJS.activity/lib/tutorial.js) to see how.

**Comment by eMBee** [comment] 2019-10-03 07:37
Abecedarium is just one of the activities that we think could benefit from a tutorial. but the title change is fine. we'll likely move on to other things once we created a tutorial for abecedarium. i expect that after that we'll write up some documentation on how to add such a tutorial to an activity, and add that to the tutorial for creating your own activity and then we'll look at other problems to work on.

**Comment by llaske** [comment] 2019-10-03 12:28
Cool. Will be great if you have opportunity to add a step 9 to the current tutorial to explain how to add a tutorial/help in an activity.

**Comment by jlc-png** [comment] 2019-10-20 03:54
We added the requirement for tutorial.
https://github.com/SamuraiNights/sugarizer/commit/c621738da6a31f1e79d341e0cd2f29b55eb877bf
But when we tried to test it ,and then we get the error below:

**Comment by SamuraiNights** [comment] 2019-10-20 03:55
Error message:
require.js:1765 Uncaught Error: Mismatched anonymous define() module: function(o){return t.Tour=e(o)}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:159)
    at intakeDefines (require.js:1192)
    at Object.localRequire [as require] (require.js:1366)
    at requirejs (require.js:1691)
    at Function.req.config (require.js:1699)
    at loader.js:1

**Comment by llaske** [comment] 2019-10-21 15:38
Hmmm. I think it means that require.js can't find your new `tutorial.js` file.
Try to put it in the `lib` directory or (better) reference it with `"activity/tutorial"` instead of `"tutorial"` in your [define](https://github.com/SamuraiNights/sugarizer/commit/c621738da6a31f1e79d341e0cd2f29b55eb877bf#diff-60678f5de4c62a92da84256477149677R3) because [this line](https://github.com/llaske/sugarizer/blob/dev/activities/Abecedarium.activity/js/loader.js#L4) means that file with `activity` prefix should be find in `js` directory.

**Comment by llaske** [comment] 2019-12-26 20:57
Fixed in https://github.com/llaske/sugarizer/pull/527

**Comment by llaske** [comment] 2020-01-02 10:57
Duplicate https://github.com/llaske/sugarizer/issues/434

**Closed by llaske** 2020-01-02 10:57 UTC
Labels: documentation
