### ISSUE TITLE
Speech and Face Palettes of speak activity doesn't work on touch screen

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#764] opened 2020-03-31 14:10 UTC
The sliders of speech and face palettes doesn't work on touch screen.

**Comment by llaske** [comment] 2020-03-31 19:48
Can't reproduce it, neither on iOS, neither on Android, neither emulated devices on the browser.

**Comment by prakashujjwal1010** [comment] 2020-03-31 20:06
![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/40318927/78070137-e4eaef00-73b8-11ea-80bb-2e1833f7d08c.gif)
the same problem persists on [sugarizer.com](https://try.sugarizer.org/) and also on android app.

**Comment by llaske** [comment] 2020-03-31 20:38
Okay. You're right.

**Comment by llaske** [comment] 2020-04-02 20:20
Fixed in https://github.com/llaske/sugarizer/pull/765

**Closed** 2020-09-23 19:33 UTC
Labels: bug, to be release
