### ISSUE TITLE
Player without face and color

### ISSUE THREAD

**Issue by hackorlyf** [llaske/sugarizer#1536] opened 2024-02-21 15:18 UTC
![PlayerNotSpawned](https://github.com/llaske/sugarizer/assets/130314506/4caf7624-869c-4a5c-a110-8d9b245f1462)

hey @llaske there are times I faced this minor bug on maze web activity where the player initially is faceless and of a grey color until and unless we give it an input. This is at total random and I had to restart twice from start to re-create it. I want to work on it.

**Comment by llaske** [comment] 2024-02-22 20:50
Can't reproduce it on my side. Try to find the sequence to reproduce it.

**Comment by hackorlyf** [comment] 2024-02-22 21:24
Okay I'll look into it.

**Comment by hackorlyf** [comment] 2024-02-24 20:12
@llaske just keep restarting the maze web activity by the button provided in the activity itself and play upto 7-8 level. It shows at the start state so don't give any input until the whole maze is loaded. You'll be able to reproduce it somewhere in between restarting 3-4 times.

**Comment by llaske** [comment] 2024-02-24 20:18
You're right, I've reproduced it

![image](https://github.com/llaske/sugarizer/assets/981841/bf049613-619d-47ae-b46c-69cdca7597b4)

**Comment by hackorlyf** [comment] 2024-02-24 20:21
I wanna contribute in helping you fix this bug

**Comment by llaske** [comment] 2024-02-24 20:29
You're welcome to send a PR

**Comment by hackorlyf** [comment] 2024-02-24 20:42
any idea what part of code might be causing this bug?

**Comment by llaske** [comment] 2024-02-24 20:42
nope

**Comment by sonisumit7904** [comment] 2024-02-29 02:00
There might be a refress action being performed after every input, because of which after input the face is visible, but maybe sometimes at the start of the game, that refresh action doesn't work, 
You could use this as a starting point for searching the bug.

**Comment by hackorlyf** [comment] 2024-02-29 10:11
Thank you so much @sonisumit7904 Got stuck sometime ago but I'll look further into it.

**Comment by sonisumit7904** [comment] 2024-02-29 12:24
@hackorlyf Happy to help!

**Comment by llaske** [comment] 2024-03-02 20:43
Fixed in https://github.com/llaske/sugarizer/pull/1541

**Closed** 2024-04-10 19:51 UTC
Labels: bug, to be release
