### ISSUE TITLE
There is sometimes a difference between the list of connected users in presence palette 

### ISSUE THREAD

**Issue by prakashujjwal1010** [llaske/sugarizer#822] opened 2020-06-25 13:40 UTC
when connected to ' dev.sugarizer.org' server there is a difference in the list of connected users in presence palette among the connected users.
for example:
for the host 'okub'
![Screenshot from 2020-06-25 17-50-16](https://user-images.githubusercontent.com/40318927/85719551-287d9c80-b70d-11ea-934d-5879d901d1e3.png)

but for the user joined 'okaypudio'
![Screenshot from 2020-06-25 17-52-32](https://user-images.githubusercontent.com/40318927/85719606-34695e80-b70d-11ea-8562-38ebf590da53.png)

and when the host leaves the activity, the error pops up in the console of other users 
`Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at Array.<anonymous> (presencepalette.js:54)
    at WebSocket.socket.onmessage (presence.js:56)`

this situation doesn't occurs when connected to local server.
to get replicate this issue, maybe you have to change the network setting at your end and try more than once. as sometimes everything works fine but mostly this situation occurs. the reason will be likely to be same as discussed in #810. 
will be very helpful , if other contributors can verify this issue.

**Comment by llaske** [comment] 2020-06-28 19:50
I've reproduced it by adding a tempo before accepting request on the server.

**Comment by llaske** [comment] 2020-06-28 20:32
I've create a fix in https://github.com/llaske/sugarizer/pull/824 

@prakashujjwal1010 could you test on your side?

It's not a definitive fix since there is currently no choice to use a tempo to detect connection. But it should happen more rarely now. Plus console error should disappear now.

**Comment by prakashujjwal1010** [comment] 2020-06-28 22:42
@llaske , i have tested it (also by changing network throttling) and it is working fine. now the list of connected users is same for all the users.The issue is resolved now. Thanks.

**Comment by llaske** [comment] 2020-06-29 19:56
Fixed in https://github.com/llaske/sugarizer/pull/824

@prakashujjwal1010 and @dhruvmisra , please report the fix in your current activity.

**Closed** 2020-09-23 19:33 UTC
Labels: bug, to be release
