### ISSUE TITLE
Stop button not visible in Scratch activity on small screens

### ISSUE THREAD

**Issue by abhishektanwar** [llaske/sugarizer#715] opened 2020-03-19 17:30 UTC
Irresponsive screen and button to stop the activity is not visible.

![WhatsApp Image 2020-03-19 at 10 56 41 PM](https://user-images.githubusercontent.com/40486188/77096214-0355ff80-6a35-11ea-9bd7-96f2d21b0811.jpeg)

**Comment by llaske** [comment] 2020-03-21 09:31
Clearly the Scratch activity is not adapted to be use on a small screen.

BTW you're right for the Stop button. Following rules [here](https://github.com/llaske/sugarizer/issues/422), it should be present to allow the user to quit the activity.

Can't reproduce the "irresponsive" screen you mention. It's always possible to drag&drop actions.

**Comment by abhishektanwar** [comment] 2020-03-21 18:03
By "irresponsive" screen I mean the non-adaptiveness of the activity towards the small screen devices.

**Comment by llaske** [comment] 2020-03-28 09:53
Fixed in https://github.com/llaske/sugarizer/pull/738

**Closed** 2020-09-23 19:33 UTC
Labels: bug, to be release
