### ISSUE TITLE
Keyboard overlaps input fields on Android

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer#739] opened 2020-03-25 12:12 UTC
A major known bug in the Android app is the overlap of virtual keyboard on input fields and text areas. Login screens use a hack (increasing bottom padding) to deal with this although causes entire UI to stay on top.
Other activities such as Get Things Done, Markdown, Writer, etc show this problem once the input focus moves below the keyboard.

![20-03-25-17-08-57](https://user-images.githubusercontent.com/40134655/77533049-2e6ca300-6ebc-11ea-8824-26a734f8fe78.gif)

![20-03-25-17-10-04](https://user-images.githubusercontent.com/40134655/77533183-6c69c700-6ebc-11ea-9113-d99590a17cdb.gif)

I will propose a solution in my next PR.

**Comment by llaske** [comment] 2020-04-04 09:40
Yes, that's true.
The issue is also on iOS thought it's still possible to scroll the screen even when the virtual keyboard is there.

**Comment by llaske** [comment] 2020-04-04 19:54
Fixed in https://github.com/llaske/sugarizer/pull/740

**Closed** 2020-09-23 19:33 UTC
Labels: bug, to be release
