### ISSUE TITLE
excessive zoom leads to text disappearence in Calligra Activity 

### ISSUE THREAD

**Issue by Swayamsvk** [llaske/sugarizer#788] opened 2020-04-25 04:41 UTC
![calligra](https://user-images.githubusercontent.com/42679893/80271340-f768f780-86dc-11ea-8549-ae87ec471dbb.gif)

**Comment by Swayamsvk** [comment] 2020-04-25 04:45
I don't know the best solution to this as limiting the magnification leads to different sizes for different letters and even shapes. If anyone can suggest something please let me know.

**Comment by llaske** [comment] 2020-04-25 14:16
It's not a bug in my opinion: whatever you zoom there is always a time where the object will be invisible.

**Comment by Swayamsvk** [comment] 2020-04-26 14:18
How about we add a drag feature as in shared notes activity by this way we can view the shape by just dragging the screen.

**Comment by llaske** [comment] 2020-04-26 19:57
Could be a good idea but difficult to implement because drag is already use for drawing

**Comment by Swayamsvk** [comment] 2020-04-26 20:50
I think you are right @llaske .

**Closed** 2020-04-26 20:50 UTC
