### ISSUE TITLE
background colour of journal-container and body are same in somes activities

### ISSUE THREAD

**Issue by Ayeshashaik759** [llaske/sugarizer#1181] opened 2023-02-02 06:49 UTC
when we click on insert option in write activity then a pop up opens in that when we go to search in abecedarium activity then as the background colour of the journal-container and body are same due to this there is no special highligth for background of scrollbar

![Screenshot (123)](https://user-images.githubusercontent.com/101845170/216251588-7abb67d1-12ef-4c78-959f-efc361e40f14.png)
  I just want to suggest that it will nice if the scroll bar have some background colour which can be implemented by changing the background colour of the journal-container. @llaske please share your view on this

somewhat like this 
![Screenshot (124)](https://user-images.githubusercontent.com/101845170/216252040-614f5a23-f65d-481c-b4a5-046bbff78b5b.png)

**Comment by llaske** [comment] 2023-02-04 21:45
Hmmm. Why not?
BTW I'm not sure that fixing this without side effect is easy.
This feature rely both on CSS and JS components.

**Comment by Ayeshashaik759** [comment] 2023-02-05 09:01
I tried to make the changes by changing the code in activities/Write.activity/css/quill/quill.core.css file. By manual testing (i.e by opening it in browser) I didn't observe any side effects. so @llaske please check the pr and share your view on it. If any side effects occur I will try resolve them.

**Comment by llaske** [comment] 2023-02-05 09:47
You must not change styles in external libraries because if the library is upgraded your change will be lost.
Plus the issue is the same in other activities (Write for example) so it's not related to Quill library.

**Comment by Ayeshashaik759** [comment] 2023-02-05 09:53
Ok i will not change the external libraries instead i will try to get the excepted changes using activity.css

**Comment by Ayeshashaik759** [comment] 2023-02-05 10:13
@llaske I think now it is working fine this time I made changes to the activity.css. And the remaining scrollbars are also working fine without any change. I reopened the pr please share your view on it.
![Screenshot (126)](https://user-images.githubusercontent.com/101845170/216813074-f0a6017f-a29d-44ca-8bd5-e89d40f76988.png)

**Comment by llaske** [comment] 2023-02-09 21:23
Same issue in Paint, Shared Notes and Fototoon.

**Comment by Ayeshashaik759** [comment] 2023-02-10 17:23
All the activities inherit same properties and opacity from the library lib/picoModel.js but still difference occurs. Another way is to solve this issue and make the scrollbar visible is to change the opacity for this activities but confused with were to make the changes as the changes are not applied by making changes to acticity.css. Ans as we cannot make changes to the libraries.

**Comment by llaske** [comment] 2023-02-11 21:43
Fixed in https://github.com/llaske/sugarizer/pull/1184

**Closed** 2023-03-28 20:17 UTC
Labels: enhancement, to be release
