### ISSUE TITLE
Issues Running in Chrom

### ISSUE THREAD

**Issue by BlueJay89** [llaske/sugarizer#785] opened 2020-04-20 01:13 UTC
I am having an issue running sugarizer in chrome. 

Chrome Version 81.0.4044.113 (Official Build) (64-bit)

Windows 10 Home

 Attached are screenshots of my issues.

1.  When attempting to initialize the software from withing the command prompt or from the run function using

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files

I simply see chrome open to a my home page

2. When I add the index.html at the end of such a command prompt

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files index.html

Chrome opens with a search of the phrase index.html

3.  If I use a Ctr-O in chrome and select the index.html file, then I see the sugarizer main login screen but it immediately becomes grayed out

4. Upon "right click" -> "inspect" there are error listed in the html code, but I don't know anything about html to sort it out

![Correct Initialization Wrong Result](https://user-images.githubusercontent.com/59810050/79704849-62e83a80-8281-11ea-99a7-c95ce92f6e63.PNG)
![Grayed Out](https://user-images.githubusercontent.com/59810050/79704856-667bc180-8281-11ea-8378-5280740784bb.PNG)
![html errors 1](https://user-images.githubusercontent.com/59810050/79705131-937ca400-8282-11ea-9e58-c7ee5fe056c7.PNG)
![html errors 2](https://user-images.githubusercontent.com/59810050/79705132-937ca400-8282-11ea-97df-16c9586c7169.PNG)

**Comment by llaske** [comment] 2020-04-20 19:17
It's an usual error.
As the first error message said `Access to XMLHttpRequest ... blocked`, it's a security error.
It should be fixed by the  `--allow-file-access-from-files` option but the option could not be taken into account if there is a running Chrome instance.
Could you ensure that there is no other running Chrome instance when you launched the command?

**Comment by BlueJay89** [comment] 2020-04-20 23:31
I will double check.  I thought I had before which is when I got the strange search page.  I will try again though.

**Comment by BlueJay89** [comment] 2020-04-20 23:37
> 
> 
> It's an usual error.
> As the first error message said `Access to XMLHttpRequest ... blocked`, it's a security error.
> It should be fixed by the `--allow-file-access-from-files` option but the option could not be taken into account if there is a running Chrome instance.
> Could you ensure that there is no other running Chrome instance when you launched the command?



> 
> 
> I will double check. I thought I had before which is when I got the strange search page. I will try again though.

I ensured no instances of chrome or any other web browser were running using task manager.  Then proceeded to attempt to use the --allow-file-access-from-files command.  An instance of chrome opened up, then said the url could not be reached, then went the strange search result page I showed in one of the screen caps I posted.

**Comment by llaske** [comment] 2020-04-21 16:14
Hmmm. Very strange. I've tested with the same version than you and it works on my side.
Plus your error message is very clear about the problem.

Could you set the current directory to the Sugarizer location before launching Chrome?
Once again, ensure first that no Chrome instance are running (to be sure reboot your computer).
Then open a command line and do something like that:

```
D:
cd Program%20files/sugarizer-lite-master
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files index.html
```

**Comment by BlueJay89** [comment] 2020-04-23 23:46
That is what I've been doing, it has not been successful.

**Comment by jrtechs** [comment] 2020-04-24 13:30
running with the command on linux (manjaro):

```
chromium --allow-file-access-from-files index.html
```

![Screenshot_2020-04-24_09-29-43](https://user-images.githubusercontent.com/13894625/80217581-f1f0ac00-860d-11ea-8d87-5d8cb4c37fa5.png)

I get a clear screen with a single error in the console. I have no other instances of chromium running.

I got this working again after clearing all cache on my web browser

**Comment by llaske** [comment] 2020-04-24 19:21
That's better :-) Now,  clear your browser cache, it should work.

**Comment by BlueJay89** [comment] 2020-05-03 18:58
@llaske, I have reached the end of the semester in the course I am in that has required I attempt to use sugarizer.  While I cannot guarantee I will discontinue attempting to get this to work, it is no longer priority for me.  I appreciate the help you've provided and hope this issue can be solved for anyone else who may experience it.

I still have yet to get this to work on my personal computer. 

- I've cleared my browser cache and history.

- I've ensured via task manager that no instances of chrome are running

- I've set the current directory to Sugarizer before running chrome
`D:\Program Files\sugarizer-lite\`

- I've opened chrome
`C:\Program Files (x86)\Google\Chrome\Applications\chrome.exe --allow-file-access-from-files`

- I've attempted to open sugarizer in that instance of chrome using ctrl-o and selecting the index.html file

I still see a grayed out screen of sugarizer as per my original submitted image.  I cannot click on anything and still see the html errors.

**Comment by llaske** [comment] 2020-05-03 19:34
Thanks for your detailed description. But it's very important to use to be able to reproduce the issue.
Could you confirm you've got always the same error in the console?

**Comment by BlueJay89** [comment] 2020-05-04 14:09
The list of errors I have seen in the console have been the same every time that I have also seen the sugarizer main screen.  In this situation the screen is grayed out and inaccessible with no ability to interact with it in any way.

**Comment by llaske** [comment] 2020-05-04 20:44
Thanks. The issue is not reproducible on our side with your description.
 I'm closing the issue. Will reopen if we could reproduce it.

**Closed by llaske** 2020-05-04 20:44 UTC
