### ISSUE TITLE
Turtle Blocks Activity hangs on Android App

### ISSUE THREAD

**Issue by manki11** [llaske/sugarizer#185] opened 2018-01-29 19:32 UTC
The turtle blocks activity hangs in Android App, when the Load Samples from web icon is clicked (world icon in top right menu). After clicking on the button , any other click after that registers as a load samples from web.

![error](https://user-images.githubusercontent.com/25136650/35530034-dfa2a874-0558-11e8-9933-b88b363562fd.gif)

Not facing any similar behaviour on sugarizer web.

Device Tested on-
Oneplus 5T
Android 7.0.1

**Comment by llaske** [comment] 2018-02-24 21:46
Seems that load samples don't work on web version.
There is a JavaScript issue here: https://github.com/llaske/sugarizer/blob/dev/activities/TurtleBlocksJS.activity/js/samplesviewer.js#L213

<img width="654" alt="image" src="https://user-images.githubusercontent.com/981841/36635408-856189c8-19b4-11e8-97b7-892f7fbfb19e.png">

**Comment by divyabaid16** [comment] 2018-03-07 10:37
I would like to work on this issue. Can you plz guide me ?

**Comment by llaske** [comment] 2018-03-07 20:30
Turtle Blocks activity come from https://github.com/walterbender/turtleblocksjs.git .
I suggest you to fork this repository, and try to understand how it works by studying the code.
Then you could see what's wrong when running on the Sugarizer environment.

**Comment by utkarsh-raj** [comment] 2019-02-24 09:51
https://github.com/llaske/sugarizer/pull/279#issue-255672546

A part of the error has been fixed by cleaning the String before parsing with the parse function. I cannot test the complete functions because the sugarizer server probably does not allow the request without CORS headers which are not present by default in the request.

Nonetheless, the problem is fixed. Please review @llaske .

**Comment by utkarsh-raj** [comment] 2019-02-26 17:39
The commit is updated @llaske .

**Comment by llaske** [comment] 2019-03-04 21:51
Fixed in https://github.com/llaske/sugarizer/pull/279

**Comment by llaske** [comment] 2019-09-26 20:41
Closed in https://github.com/llaske/sugarizer/commit/dd3c58d56981e4dfa6d94601b95d7117a3bc9241

**Closed by llaske** 2019-09-26 20:41 UTC
Labels: bug, to be release
