### ISSUE TITLE
Improvement in #color-button-fill in paint activity

### ISSUE THREAD

**Issue by S-kus** [llaske/sugarizer#987] opened 2022-03-03 17:40 UTC
In the `#color-button-fill` tool-button of **Paint activity**, we can set RGB colors using the slider. As shown:

![paint](https://user-images.githubusercontent.com/86892991/156620474-ce715558-1bf1-4091-b513-3c3835624ac3.png)

I would like to propose the feature:
- color range of RGB as a value with the slider.
- hex code input button.
- directly input the RGB values as well.
It will be more user-friendly and children can explore more. As well as if anyone wants to use a particular color value, he can set it easily.

**Comment by S-kus** [comment] 2022-03-03 17:43
@llaske could you please go over the proposed feature and let me know will it be good for the activity or not?
If it's fine I would like to work on the issue.

**Comment by codebloded** [comment] 2022-03-03 19:57
> @llaske could you please go over the proposed feature and let me know will it be good for the activity or not? If it's fine I would like to work on the issue.

Yes i think it'll be a nice feature for children

**Comment by llaske** [comment] 2022-03-03 20:39
I'm not in favor of that. Sugarizer is a tool for children, some children are not able to read numbers.
Plus they don't need to reproduce an exact color so we don't need this level of precision.

**Comment by AnandChourasia007** [comment] 2022-03-04 07:16
Hey @S-kus , I think you should close this issue now, since this enhancement is not required at the moment.

**Comment by S-kus** [comment] 2022-03-04 07:55
> I'm not in favor of that. Sugarizer is a tool for children, some children are not able to read numbers. Plus they don't need to reproduce an exact color so we don't need this level of precision.

Thanks, @llaske I understood, so I am closing this issue.

**Closed** 2022-03-04 07:59 UTC
